# Generated by Django 4.0.1 on 2022-01-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=120),
        ),
    ]
