# Generated by Django 4.0.1 on 2022-01-21 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ADMITTED', 'admitted'), ('NOT_INTERESTED', 'not_interested'), ('FOLLOWUP', 'followup')], default='FOLLOWUP', max_length=120)),
                ('followup_date', models.DateField(null=True)),
                ('enquiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.course')),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
